services:
  db:
    image: postgres:16
    container_name: bankcards-db
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bankcards-app
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/bankcards
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: JWT_SECRET=my-super-secret-key-for-jwt-signing-1234567890
      APP_ENCRYPTION_KEY: 1234567890abcdef
    ports:
      - "8080:8080"

volumes:
  postgres_data:
